server:
  port: 0

spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:postgresql://localhost:5432/orderservice?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: wikiwoo
    password: ipass
    driver-class-name: org.postgresql.Driver
    tomcat:
      test-while-idle: true
    dbcp2:
      validation-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
